Develop
mate-academy/react_redux-list-of-todos pull request #196
Opened 2022-04-21 13:18 UTC by AnnSerdechna

[Demo]( https://annserdechna.github.io/react_redux-list-of-todos/)

2022-04-22 08:10 UTC, Ihor-Karpyn requested changes

2022-04-22 08:10 UTC, Ihor-Karpyn commented on src/App.tsx
```suggestion
```

2022-04-22 08:10 UTC, Ihor-Karpyn commented on src/App.tsx
> +  );
:harold

2022-04-22 08:10 UTC, Ihor-Karpyn commented on src/App.tsx
>        <h1>Redux list of todos</h1>
remove comments

2022-04-22 08:10 UTC, Ihor-Karpyn commented on src/components/TodoItem/TodoItem.tsx
> +    await removeTodo(todoId);
check is comment deleted

2022-04-22 08:10 UTC, Ihor-Karpyn commented on src/components/TodoList/TodoList.tsx
> +export const TodoList: FC<Props> = memo(({ todos }) => {
get todos using use selector hook, but not from props

2022-04-22 08:10 UTC, Ihor-Karpyn commented on src/components/UserDetails/UserDetails.tsx
> +  const [user, setUser] = useState<User | null>(Object);
save user in redux

2022-04-22 08:10 UTC, Ihor-Karpyn commented on src/data/users.api.ts
> +export const getUser = (userId: number): Promise<User> => getData(`${ENDPOINTS.users}/${userId}`);
```suggestion
export const getUserById = (userId: number): Promise<User> => getData(`${ENDPOINTS.users}/${userId}`);
```

2022-04-28 07:10 UTC, solaryasha approved these changes

2023-07-02 14:28 UTC, closed without merging