implement redux store with toolkit (createSlice)
mate-academy/react_redux-list-of-todos pull request #210
Opened 2022-05-31 22:02 UTC by misha200119

[DEMO LINK](https://misha200119.github.io/react_redux-list-of-todos/)

2022-06-01 06:58 UTC, Anastasiia-Svintsova requested changes
Good job, just delete useless files (Finish, Start)

2022-06-01 06:58 UTC, Anastasiia-Svintsova commented on src/components/TodoList/TodoList.tsx
> +          return includePattern && toDo.completed === true;
```suggestion
          return includePattern && toDo.completed;
```

2022-06-01 06:58 UTC, Anastasiia-Svintsova commented on src/components/TodoList/TodoList.tsx
> +          return includePattern && toDo.completed === false;
```suggestion
          return includePattern && !toDo.completed;
```

2022-06-01 06:58 UTC, Anastasiia-Svintsova commented on src/index.tsx
>      </BrowserRouter>
Router можна видалити, якщо не використовуєш

2022-06-01 07:44 UTC, MaksimusCRS requested changes
Не рендерь кнопку юзера если нет инфо про него
<img width="822" alt="image" src="https://user-images.githubusercontent.com/92159085/171353768-b869aaf2-04bb-4492-a278-8814078afb7b.png">

2022-06-01 08:55 UTC, MaksimusCRS requested changes
<img width="753" alt="image" src="https://user-images.githubusercontent.com/92159085/171366772-ee92888a-7107-484b-af76-23b468ef468a.png">
А где кнопочки, что бы удалять посты?

2022-06-02 10:17 UTC, MaksimusCRS approved these changes
Well done 🚀

2022-06-02 10:17 UTC, MaksimusCRS commented on src/store/toDosSlice.ts
> +        [filtered[i], filtered[j]] = [filtered[j], filtered[i]];
Smart solution, but hard to understand

2022-06-02 10:17 UTC, MaksimusCRS commented on src/store/toDosSlice.ts
> +// immutable state based off those changes
🔥

2022-06-02 10:17 UTC, MaksimusCRS commented on src/store/index.ts
> +  // eslint-disable-next-line max-len
remove it

2022-06-02 10:17 UTC, MaksimusCRS commented on src/components/TodoList/TodoList.tsx
> +              dispatch(setFilterCompletedToDos(target.value as unknown as FilterToDosBy));
:harold:

2022-06-02 10:17 UTC, MaksimusCRS commented on src/components/CurrentUser/CurrentUser.tsx
> +        : (
```suggestion
      ) : (
```

2022-06-02 10:17 UTC, MaksimusCRS commented on src/App.tsx
> +// import { useAppSelector, useAppDispatch } from './typedHooks/hooks';
remove it

2025-08-10 12:44 UTC, closed without merging