Solution
mate-academy/react_redux-list-of-todos pull request #215
Opened 2022-06-01 17:41 UTC by YegorKochetkov

[DEMO LINK](https://YegorKochetkov.github.io/react_redux-list-of-todos/)

2022-06-02 11:41 UTC, lem47 commented on src/App.tsx
> +  }, []);
Это можно перекинуть в компонент по работе с юзерами

2022-06-02 11:42 UTC, lem47 commented on src/api/api.ts
> +  return todos;
return response.json();

2022-06-02 11:42 UTC, lem47 commented on src/api/api.ts
> +
```suggestion
return response.json();
```

2022-06-02 11:42 UTC, lem47 commented on src/api/api.ts
> +  return todos;
```suggestion
  return response.json();
```

2022-06-02 11:43 UTC, lem47 commented on src/api/api.ts
> +  return user;
```suggestion
  return response.json();
```

2022-06-02 11:47 UTC, lem47 commented on src/types/Todo.ts
> +  updatedAt: string,
You don't need this

2022-06-02 11:47 UTC, lem47 commented on src/types/Todo.ts
> +  updatedAt: string,
You don't need this

2022-06-02 11:48 UTC, lem47 commented on src/types/User.ts
> +  phone: string,
```suggestion
  id: number,
  name: string,
  email: string,
  phone: string,
```

2022-06-02 11:50 UTC, lem47 requested changes
Молодец!
Но можно пофиксить несколько моментов ;)

2022-06-03 06:47 UTC, MaksimusCRS approved these changes
Well done

2022-06-03 06:47 UTC, MaksimusCRS commented on src/store/index.ts
> +export const getFilteredTodos = (state: RootState) => state.filteredTodos;
i think you can decrease amount 🤔

2022-06-03 06:47 UTC, MaksimusCRS commented on src/components/TodoList/TodoList.tsx
> +            <option value={Status.Completed}>completed</option>
u can use map here as well

2022-11-01 23:31 UTC, closed without merging