reduser with type mistake
mate-academy/react_redux-list-of-todos pull request #222
Opened 2022-06-02 14:26 UTC by serhii-naumenko

[DEMO LINK](https://serhii-naumenko.github.io/react_redux-list-of-todos/)

2022-06-03 13:12 UTC, Yurii837 requested changes
Все структуризировано и понятно, но хочется увидеть как код работает)

2022-06-06 06:58 UTC, Andr1yK requested changes
U need some fixes, but it`s GJ 🔥

2022-06-06 06:58 UTC, Andr1yK commented on src/App.tsx
> +// import { Todo } from './types/TodoType';
remove comments

2022-06-06 06:58 UTC, Andr1yK commented on src/api/api.ts
> +  return gottenTodos;
optional))

```suggestion
  return response.json();
```

2022-06-06 06:58 UTC, Andr1yK commented on src/api/api.ts
> +// }
remove comments)

2022-06-06 06:58 UTC, Andr1yK commented on src/components/CurrentUser/CurrentUser.tsx
> +  const resetUserId = useCallback((value: number) => {
You may not need `value ` (the name says - this function just set zero)

2022-06-06 06:58 UTC, Andr1yK commented on src/components/TodoList/TodoList.tsx
> +  const [status, setStatus] = useState('all');
use enum

2022-06-06 06:58 UTC, Andr1yK commented on src/components/TodoList/TodoList.tsx
> +  const deleterTodoByUserId = useCallback((id: number) => {
```suggestion
  const deleteTodoByUserId = useCallback((id: number) => {
```

2022-06-06 06:58 UTC, Andr1yK commented on src/components/TodoList/TodoList.tsx
> +                    onClick={() => deleterTodoByUserId(Number(todo.id))}
todo.id != ByUserId, rename this fucntion

2022-06-06 06:58 UTC, Andr1yK commented on src/types/TodoType.ts
> +export interface User {
One type = one file

2022-06-07 08:02 UTC, Andr1yK approved these changes

2022-06-21 14:43 UTC, closed without merging