init
mate-academy/react_redux-list-of-todos pull request #761
Opened 2024-01-03 15:11 UTC by MaksymKos

https://maksymkos.github.io/react_redux-list-of-todos/

2024-01-03 18:59 UTC, Andriy-Shymkiv requested changes

2024-01-03 18:59 UTC, Andriy-Shymkiv commented on src/App.tsx
> +      {currentTodo !== null && (
```suggestion
      {currentTodo && (
```

2024-01-03 18:59 UTC, Andriy-Shymkiv commented on src/components/TodoModal/TodoModal.tsx
> +      }
where is catch?

2024-01-04 12:04 UTC, anastasiiavorobiova approved these changes
Great work!

2024-10-14 06:09 UTC, closed without merging