send my code for analysis
mate-academy/react_redux-list-of-todos pull request #801
Opened 2024-02-07 14:21 UTC by OPTIMISTIXX

[DEMO LINK](https://OPTIMISTIXX.github.io/react_redux-list-of-todos/)

2024-02-07 16:52 UTC, sTorba24 requested changes
Good start! Request review when you finish with task

2024-02-07 16:52 UTC, sTorba24 commented on src/components/TodoFilter/TodoFilter.tsx
> +  const handleQuery = (event: React.ChangeEvent<HTMLInputElement>) => {
![image](https://github.com/mate-academy/react_redux-list-of-todos/assets/55200530/21dd1027-6902-4183-8748-6eec9a8a369d)

2024-02-09 11:39 UTC, anastasiiavorobiova requested changes
Great work! Almost done: 
<img width="747" alt="Screenshot 2024-02-09 at 13 32 54" src="https://github.com/mate-academy/react_redux-list-of-todos/assets/135232001/1cb65363-793e-4f44-9401-8f6c12f836c8">
Consider removing this button if the query is empty

2024-02-09 11:39 UTC, anastasiiavorobiova commented on src/components/TodoList/TodoList.tsx
> +            <tr data-cy="todo">
Consider using keys while rendering lists

2024-02-12 11:33 UTC, anastasiiavorobiova approved these changes
Great work!

2025-08-04 16:12 UTC, closed without merging