react_redux-list-of-todos
mate-academy/react_redux-list-of-todos pull request #951
Opened 2024-07-17 09:05 UTC by svyatoslavPy

[DEMO LINK](https://svyatoslavPy.github.io/react_redux-list-of-todos/)

2024-07-17 13:58 UTC, anastasiiavorobiova requested changes
Consider fixing previous comments and the test 
<img width="1111" alt="Screenshot 2024-07-17 at 16 57 17" src="https://github.com/user-attachments/assets/146fee31-28b8-4d8c-950f-7afa177176a6">

2024-07-18 15:08 UTC, anastasiiavorobiova requested changes
Consider fixing previous issues

2024-07-18 15:08 UTC, anastasiiavorobiova commented on src/App.tsx
> +      <TodoModal showModal={showModal} onCloseModal={handleCloseModal} />
```suggestion
      showModal && <TodoModal onCloseModal={handleCloseModal} />
```

2024-07-18 15:30 UTC, etojeDenys approved these changes
good job

2024-07-18 15:30 UTC, etojeDenys commented on src/components/TodoModal/TodoModal.tsx
> +        {!loading && <ModalCard onCloseModal={onCloseModal} />}
better to simplify it using the ternary operator

2024-07-18 15:30 UTC, etojeDenys commented on src/components/TodoList/TodoList.tsx
> +    <>
looks like a redundant fragment

https://react.dev/reference/react/Fragment#usage

2024-09-28 18:14 UTC, closed without merging